version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "4000:5173"
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - app-network

networks:
  app-network:
    external: true